apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: staticwebsite2
spec:
  backend: "gs://pulumi-state-bucket-test"

  secretsProvider: "gcpkms://projects/bold-proton-389120/locations/us-central1/keyRings/teste/cryptoKeys/pulumi"
  stack: meu-bucket-321321dsads2
  programRef:
    name: staticwebsite
  destroyOnFinalize: true
  config:
    gcp:region: us-central1
    gcp:project: bold-proton-389120
    name: meu-bucket-321321dsads2