steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bold-proton-389120/bucket-factory:v1', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bold-proton-389120/bucket-factory:v1']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bucket-factory'
      - '--image'
      - 'gcr.io/bold-proton-389120/bucket-factory:v1'
      - '--region'
      - 'us-central'
images:
  - 'gcr.io/bold-proton-389120/bucket-factory:v1'